import React, { useState } from 'react';
import { Download, FolderArchive, FileCode, Check, Folder, Sparkles, Code } from 'lucide-react';
import JSZip from 'jszip';
import { TranslatedScenePlan } from '../types';

interface GodotProjectExporterProps {
  plan: TranslatedScenePlan;
}

export const GodotProjectExporter: React.FC<GodotProjectExporterProps> = ({ plan }) => {
  const [selectedFile, setSelectedFile] = useState<string>('project.godot');
  const [isExporting, setIsExporting] = useState<boolean>(false);
  const [exportedSuccess, setExportedSuccess] = useState<boolean>(false);

  // File tree mapping
  const fileContents: Record<string, string> = {
    'project.godot': plan.projectGodotContent || `; Engine configuration file for ${plan.godotVersion}\nconfig_version=5\n\n[application]\nconfig/name="${plan.sceneTitle}"\nrun/main_scene="res://scenes/main_scene.tscn"\n`,
    'scenes/main_scene.tscn': plan.tscnContent,
    'README.md': `# ${plan.sceneTitle}

An AI-architected Godot Engine scene and project generated by Godot Scene Architect.

## 🕹️ Project Overview
- **Genre**: ${plan.genre}
- **Godot Version**: ${plan.godotVersion}
- **Camera Mode**: ${plan.cameraMode}

## 🚀 How to Run in Godot
1. Open Godot 4 Engine (${plan.godotVersion}).
2. Click **Import** -> Select this project directory containing \`project.godot\`.
3. Press **F5** or Click Play in top-right to launch \`res://scenes/main_scene.tscn\`.

## 📁 Repository Structure
- \`scenes/\`: Main scene \`.tscn\` files.
- \`scripts/\`: GDScript code implementations.
- \`.github/\`: Issue templates and GitHub project automation files.
`,
    '.gitignore': `# Godot-specific ignores
.godot/
*.import
export_presets.cfg
`,
  };

  // Add GDScripts
  plan.gdscripts.forEach((sc) => {
    const cleanPath = sc.filename.replace('res://', '');
    fileContents[cleanPath] = sc.code;
  });

  // Add Issue Template
  fileContents['.github/ISSUE_TEMPLATE/godot_feature.md'] = `---
name: Godot Engine Task
about: Automated game feature or scene implementation
title: '[Godot] '
labels: 'godot-4, gdscript'
assignees: ''
---

## 🎮 Feature Objective

## 🛠️ Godot Editor Steps

## ✅ Acceptance Criteria
- [ ] Created nodes in Scene Dock
- [ ] GDScript attached and tested
`;

  const handleDownloadZip = async () => {
    setIsExporting(true);
    setExportedSuccess(false);

    try {
      const zip = new JSZip();

      // Add all files
      Object.entries(fileContents).forEach(([filePath, content]) => {
        zip.file(filePath, content);
      });

      // Add GitHub Issues markdown
      let issuesMd = `# GitHub Issues for ${plan.sceneTitle}\n\n`;
      plan.issues.forEach((iss, idx) => {
        issuesMd += `## Issue #${idx + 1}: ${iss.title}\n${iss.bodyMarkdown}\n\n`;
      });
      zip.file('.github/ISSUES_EXPORT.md', issuesMd);

      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const cleanTitle = plan.sceneTitle.toLowerCase().replace(/[^a-z0-9]/g, '_');
      a.download = `godot_scene_${cleanTitle}.zip`;
      a.click();
      URL.revokeObjectURL(url);

      setExportedSuccess(true);
      setTimeout(() => setExportedSuccess(false), 3000);
    } catch (err) {
      console.error('Error generating project ZIP:', err);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="bg-[#010409] border border-slate-800 rounded-sm p-6 shadow-2xl space-y-6 relative overflow-hidden">
      
      {/* Background Section Index Number */}
      <div className="absolute right-4 top-0 pointer-events-none select-none opacity-10 text-slate-700 font-black text-8xl md:text-9xl tracking-tighter leading-none">
        06
      </div>

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-800 relative z-10">
        <div>
          <div className="flex items-center space-x-2">
            <span className="text-xs font-mono font-bold tracking-widest text-sky-400 uppercase bg-sky-950/60 px-2 py-0.5 border border-sky-500/30">
              06 // ZIP EXPORTER
            </span>
            <h3 className="font-black text-white text-base uppercase tracking-tight flex items-center gap-2">
              <FolderArchive className="w-5 h-5 text-emerald-400" />
              Godot Project Bundle &amp; ZIP Exporter
            </h3>
          </div>
          <p className="text-xs text-slate-400 mt-1 uppercase font-mono tracking-wider">
            Download ready-to-import Godot 4 project directory with scenes, GDScripts &amp; issue templates
          </p>
        </div>

        <button
          onClick={handleDownloadZip}
          disabled={isExporting}
          className="px-5 py-2.5 rounded-sm bg-emerald-600 hover:bg-emerald-500 text-white font-mono font-bold text-xs uppercase tracking-wider flex items-center justify-center gap-2 shadow-lg shadow-emerald-600/20 border border-emerald-400/40 transition-all disabled:opacity-50 cursor-pointer"
        >
          {exportedSuccess ? (
            <>
              <Check className="w-4 h-4 text-emerald-200" />
              <span>Downloaded .ZIP!</span>
            </>
          ) : (
            <>
              <Download className="w-4 h-4" />
              <span>{isExporting ? 'Packaging ZIP...' : 'Download Godot Project (.ZIP)'}</span>
            </>
          )}
        </button>
      </div>

      {/* File Explorer Preview */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 relative z-10">
        
        {/* Left: File Tree */}
        <div className="lg:col-span-4 bg-slate-950 border border-slate-800 rounded-sm p-3">
          <div className="text-[10px] font-mono font-bold text-slate-400 uppercase tracking-widest mb-3 px-2 flex items-center gap-1.5">
            <Folder className="w-3.5 h-3.5 text-emerald-400" /> Project Structure
          </div>

          <div className="space-y-1.5">
            {Object.keys(fileContents).map((fileKey) => {
              const isSelected = selectedFile === fileKey;
              return (
                <div
                  key={fileKey}
                  onClick={() => setSelectedFile(fileKey)}
                  className={`p-2.5 rounded-sm cursor-pointer border font-mono text-xs transition-all flex items-center justify-between ${
                    isSelected
                      ? 'bg-emerald-950/60 border-emerald-500 text-white shadow'
                      : 'bg-slate-900/50 border-transparent text-slate-300 hover:bg-slate-900'
                  }`}
                >
                  <span className="truncate">{fileKey}</span>
                  <FileCode className="w-3.5 h-3.5 text-slate-500" />
                </div>
              );
            })}
          </div>
        </div>

        {/* Right: File Content Code View */}
        <div className="lg:col-span-8 bg-slate-950 border border-slate-800 rounded-sm p-4 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between border-b border-slate-800 pb-2.5 mb-3 font-mono">
              <span className="text-xs font-bold text-emerald-400 flex items-center gap-1.5">
                <Code className="w-4 h-4" /> {selectedFile}
              </span>
              <span className="text-[10px] text-slate-400">
                {fileContents[selectedFile]?.split('\n').length || 0} lines
              </span>
            </div>

            <pre className="font-mono text-xs text-slate-200 bg-[#080d1a] p-4 rounded-sm border border-slate-800 overflow-x-auto max-h-[380px] leading-relaxed">
              {fileContents[selectedFile] || '# Empty file'}
            </pre>
          </div>
        </div>

      </div>

    </div>
  );
};
